import { labels } from "@/data/labels";
import Head from "next/head";
import styles from '../../styles/Home.module.scss';
import Header from "@/components/Molecules/Header/Header";
import WindowBox from "@/components/Organism/WindowBox/WindowBox";
import Footer from "@/components/Molecules/Footer/Footer";

function index() {
    return (
        <>
            <Head>
                <title>{labels.titlePageLabel}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Header
                    title={labels.titlePageLabel}
                />
                <div className={styles.content}>
                    <WindowBox
                        title={'Hello World'}
                    />
                </div>
                <Footer />
            </main>
        </>
    )
}

export default index